name: dentistry_api
description: An Aqueduct application with a database connection and data model.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.1.0"

dependencies:
  aqueduct: ^3.1.0
  jaguar_jwt: ^2.1.6
  intl: ^0.16.1
  json_serializable: ^3.3.0



dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

dependency_overrides:
  postgres: 2.1.1
