name: dentistry_api
description: An Aqueduct application with a database connection and data model.
version: 0.0.5
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.1.0"

dependencies:
  aqueduct: ^3.1.0
  jaguar_jwt: ^2.1.6
  intl: ^0.16.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
